-- Migrations additional to existing Pantry Healthy schema. Run these once.
USE pantry_healthy;

ALTER TABLE usuarios 
    ADD COLUMN IF NOT EXISTS idade INT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS sexo VARCHAR(50) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS peso DECIMAL(6,2) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS altura DECIMAL(5,2) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS objetivo VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS nivel_atividade VARCHAR(50) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS restricao_alimentar TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS pontos INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reset_token VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS reset_expires DATETIME DEFAULT NULL;

-- ensure alimentos and alimentos_usuario exist (basic)
CREATE TABLE IF NOT EXISTS alimentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(191) NOT NULL,
  calorias INT DEFAULT 0,
  proteinas DECIMAL(6,2) DEFAULT 0,
  carboidratos DECIMAL(6,2) DEFAULT 0,
  gorduras DECIMAL(6,2) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS alimentos_usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT NOT NULL,
  alimento_id INT NOT NULL,
  quantidade DECIMAL(8,2) DEFAULT 1,
  data_adicao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  FOREIGN KEY (alimento_id) REFERENCES alimentos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
